# universe.py

STOCKS = [
    "DIXON.NS", "BSE.NS", "KPITTECH.NS", "RVNL.NS", "SUZLON.NS",
    "CUMMINSIND.NS", "PERSISTENT.NS", "POLYCAB.NS", "ASTRAL.NS", 
    "IDFCFIRSTB.NS", "FEDERALBNK.NS", "ASHOKLEY.NS", "TVSMOTOR.NS", 
    "TATAPOWER.NS", "LUPIN.NS", "AUROPHARMA.NS", "TRENT.NS", 
    "CHOLAFIN.NS", "HAL.NS", "BEL.NS", "CGPOWER.NS", "COFORGE.NS", 
    "MAZDOCK.NS", "KALYANKJIL.NS", "FACT.NS", "APOLLOTYRE.NS", 
    "ESCORTS.NS", "GMRINFRA.NS", "OBEROIRLTY.NS", "PRESTIGE.NS"
]
